---
title: "p8105_hw5_ars2376"
output: html_document
date: "2025-11-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, results = 'hide'}
library(tidyverse)
library(rvest)
library(ggplot2)
```


## Problem 1

Creating the function to get the probability at at least two people in a room of `n` people share a birthday

```{r}
bday_sim = function(n_room) {
  
  birthdays = sample(1:365, n_room, replace = TRUE) 
  
  repeated_bday = length(unique(birthdays)) < n_room
  
  repeated_bday
}

```

Run this function 10000 times for each group size between 2 and 50

```{r}
bday_results =
  expand_grid(
    bdays = 2:50, 
    iter = 1:10000
  ) |> 
  rowwise() |> 
  mutate(
    result = bday_sim(bdays)
  ) |> 
  ungroup() |> 
  group_by(bdays) |> 
  summarize(
    prob_repeat = mean(result)
  )
```

Plot that shows probability as a function of group size

```{r}
bday_results |> 
  ggplot(aes(x = bdays, y = prob_repeat)) +
  geom_point() +
  geom_line() +
  labs(
    title = "Probability of at least 2 people in a room of n people sharing a birthday",
      x = "Group Size (n)",
    y = "Probability"
  )
```

